# Daily build and release workflow.
# The Yosys version that it picks is sets in build.py.

name: build-and-release

on:
  # Run on each commit to this repo.
  push:

  # Run every day at 2AM.
  schedule:
    - cron: '0 2 * * *'

  # Allow manual activations.
  workflow_dispatch:

permissions:
  # Allow release creation
  contents: write

jobs:

  # -- Build packages for all supported architectures and
  # -- export them in a release.
  build-and-release:

    runs-on: ubuntu-22.04

    steps:


      # Release version: e.g. 0.1.2
      - name: Determine release version
        run: |
          release_version="$(date +'%Y.%m.%d')"
          echo $release_version
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV


      # Release version: e.g. 0-1-2
      - name: Determine release tag
        run: |
          release_tag="${RELEASE_VERSION//./-}"
          echo $release_tag
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV


      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: this-repo


      - name: Build package [darwin-arm64]
        run: |
          cd this-repo
          python ./build.py --platform darwin-arm64 --version $RELEASE_VERSION


      - name: Build package [darwin-x86-64]
        run: |
          cd this-repo
          python ./build.py --platform darwin-x86-64 --version $RELEASE_VERSION


      - name: Build package [linux-x86-64]
        run: |
          cd this-repo
          python ./build.py --platform linux-x86-64 --version $RELEASE_VERSION


      - name: Build package [linux-aarch64]
        run: |
          cd this-repo
          python ./build.py --platform linux-aarch64 --version $RELEASE_VERSION


      - name: Build package [windows-amd64]
        run: |
          cd this-repo
          python ./build.py --platform windows-amd64 --version $RELEASE_VERSION


      - name: Create the Release and upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{env.RELEASE_TAG}}
          name: ${{env.RELEASE_TAG}}
          body: A new release (Draft)
          files: |
            _packages/apio-oss-cad-suite-darwin-arm64-${{env.RELEASE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-darwin-x86-64${{env.RELEASE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-linux-x86-64-${{env.RELEASE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-linux-aarch64-${{env.RELEASE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-windows-amd64-${{env.RELEASE_TAG}}.tar.gz


