# Daily build and release workflow.
# The Yosys version that it picks is sets in build.py.

name: build-and-release

on:
  # Run on each commit to this repo.
  push:

  # Run every day at 2AM.
  schedule:
    - cron: '0 2 * * *'

  # Allow manual activations.
  workflow_dispatch:

permissions:
  # Allow release creation
  contents: write

jobs:

  # -- Build packages for all supported architectures and
  # -- export them in a release.
  build-and-release:

    runs-on: ubuntu-22.04

    steps:


      # E.g. "2025-11-02"
      - name: Determine release tag
        run: |
          release_tag="$(date +'%Y-%m-%d')"
          echo $release_tag
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

      # E.g. "20251102"
      - name: Determine package tag
        run: |
          package_tag="${RELEASE_TAG//-/}"
          echo $package_tag
          echo "PACKAGE_TAG=$package_tag" >> $GITHUB_ENV

      # Required by the build script to extracting windows .exe.
      - name: Install p7zip (7z command)
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full


      # Check out the this repo in the workflow work directory.
      - name: Checkout this repo
        uses: actions/checkout@v4


      - name: Create the package.json file
        run: |
          out="package.json"

          echo "{" >> ${out}
          echo "  \"name\": \"examples\"," >> ${out}
          echo "  \"description\": \"Apio examples package\"," >> ${out}
          echo "  \"version\": \"$RELEASE_TAG\"," >> ${out}
          # echo "  \"target-platform\": \"all\"" >> ${out}
          echo "  \"build-repo\": \"${{github.repository}}\"," >> ${out}
          echo "  \"workflow\": \"${{github.workflow}}\"," >> ${out}
          echo "  \"workflow-run\": \"${{github.run_id}}\"," >> ${out}
          echo "  \"time\": \"$(date +'%Y-%m-%d %H:%M:%S %Z')\"," >> ${out}
          echo "  \"commit\": \"$RELEASE_COMMIT\"" >> ${out}
          # echo "  \"file-name\": \"$PACKAGE_NAME\"" >> ${out}

          echo "}" >> ${out}

          pwd
          ls -al
          cat -n package.json

      - name: Build package [darwin-arm64]
        run: |
          pwd
          ls -al
          python ./build.py \
              --platform darwin-arm64 \
              --package-tag $PACKAGE_TAG \
              --package-json package.json


      - name: Build package [darwin-x86-64]
        run: |
          python ./build.py \
              --platform darwin-x86-64 \
              --package-tag $PACKAGE_TAG \
              --package-json package.json


      - name: Build package [linux-x86-64]
        run: |
          python ./build.py \
              --platform linux-x86-64 \
              --package-tag $PACKAGE_TAG \
              --package-json package.json


      - name: Build package [linux-aarch64]
        run: |
          python ./build.py \
              --platform linux-aarch64 \
              --package-tag $PACKAGE_TAG \
              --package-json package.json


      - name: Build package [windows-amd64]
        run: |
          python ./build.py \
              --platform windows-amd64 \
              --package-tag $PACKAGE_TAG \
              --package-json package.json


      - name: List packages
        run: |
          ls -al _packages/*


      - name: Prepare release text
        run: |
          out=RELEASE_BODY.txt
          echo "This is an automated release-and-build of the Apio oss-cad-suite package." >> $out

          echo -e "\n<br>\n" >> $out

          echo "package.json" >> $out
          echo '```' >> $out
          cat package.json >> $out
          echo '```' >> $out

          echo -e "\n<br>\n" >> $out
          cat -n $out


      - name: Create the Release and upload files
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{env.RELEASE_TAG}}
          name: ${{env.RELEASE_TAG}}
          body_path: RELEASE_BODY.txt
          preserve_order: true
          fail_on_unmatched_files: true
          files: |
            _packages/apio-oss-cad-suite-darwin-arm64-${{env.PACKAGE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-darwin-x86-64-${{env.PACKAGE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-linux-x86-64-${{env.PACKAGE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-linux-aarch64-${{env.PACKAGE_TAG}}.tar.gz
            _packages/apio-oss-cad-suite-windows-amd64-${{env.PACKAGE_TAG}}.tar.gz


