# Daily build and release workflow.
# The Yosys version that it picks is sets in build.py.

name: build-and-release

on:
  # Run on each commit to this repo.
  push:

  # Run every day at 2AM.
  schedule:
    - cron: '0 2 * * *'

  # Allow manual activations.
  workflow_dispatch:

permissions:
  # Allow release creation
  contents: write

jobs:

  # -- Build packages for all supported architectures and
  # -- export them in a release.
  build-and-release:

    runs-on: ubuntu-22.04

    steps:


      # # E.g.  "2025.11.2"
      # - name: Determine release version
      #   run: |
      #     release_version="$(date +'+%Y.%-m.%-d')"
      #     echo $release_version
      #     echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV

      # E.g. "2025-11-02"
      - name: Determine release tag
        run: |
          release_tag="$(date +'+%Y-%m-%d')"
          echo $release_tag
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

      # E.g. "2025-11-02"
      - name: Determine package tag
        run: |
          package_tag="${RELEASE_TAG//-/}"
          echo $package_tag
          echo "PACKAGE_TAG=$package_tag" >> $GITHUB_ENV


      # Required by the build script to extracting windows .exe.
      - name: Install p7zip (7z command)
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full


      # Check out the this repo in the workflow work directory.
      - name: Checkout this repo
        uses: actions/checkout@v4


      - name: Build package [darwin-arm64]
        run: |
          python ./build.py --platform darwin-arm64 --package-tag $PACKAGE_TAG


      - name: Build package [darwin-x86-64]
        run: |
          python ./build.py --platform darwin-x86-64 --package-tag $PACKAGE_TAG


      - name: Build package [linux-x86-64]
        run: |
          python ./build.py --platform linux-x86-64 --package-tag $PACKAGE_TAG


      - name: Build package [linux-aarch64]
        run: |
          python ./build.py --platform linux-aarch64 --package-tag $PACKAGE_TAG


      - name: Build package [windows-amd64]
        run: |
          python ./build.py --platform windows-amd64 --package-tag $PACKAGE_TAG


      - name: List packages
        run: |
          ls -al _packages


      - name: Create the Release and upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{env.RELEASE_TAG}}
          name: ${{env.RELEASE_TAG}}
          body: A new release (Draft)
          files:
            _packages/apio-oss-cad-suite-darwin-arm64-${{env.PACKAGE_TAG}}.zip
            _packages/apio-oss-cad-suite-darwin-x86-64${{env.PACKAGE_TAG}}.zip
            _packages/apio-oss-cad-suite-linux-x86-64-${{env.PACKAGE_TAG}}.zip
            _packages/apio-oss-cad-suite-linux-aarch64-${{env.PACKAGE_TAG}}.zip
            _packages/apio-oss-cad-suite-windows-amd64-${{env.PACKAGE_TAG}}.zip


